### PR TITLE
Handle gunzip/zlib errors

### LINKED ISSUE #528: copyfrom `Uncaught exception: Error: incorrect header check`
If you request a gzipped copyfrom sending a bad formatted gzip body (at least, we think the cause is a bad formatted gzip body), the API crashes. In the log you can see: 
```
Uncaught exception: Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:370:17)
```

The error was reported by @rafatower who could add more info

### PR DESCRIPTION
**Pull request by rafatower**
This fixes #528

### CODE REVIEW

File: app/controllers/copy_controller.js [hunk 1]
```diff
@@ -115,16 +115,16 @@ function handleCopyFrom (logger) {
 
             req
                 .on('data', data => isGzip ? metrics.addGzipSize(data.length) : undefined)
-                .on('error', err => {
```
Comment (oleurud) [inline app/controllers/copy_controller.js]: We should maintain it because if an error happens in the request we will have the same problem

Comment (oleurud) [reply app/controllers/copy_controller.js]: By the way, the new error handler is correct. Good catch

Comment (rafatower) [reply app/controllers/copy_controller.js]: OK. Then if the error handler can be specific to `Gunzip` I'd decorate the error with something like: `"Error while gunzipping: {error}"`. E.g: `"Error while gunzipping: incorrect header check"`. That would make it easier to understand for client developers (it got me crazy for a while, because I did not get any error on the client to start with).

File: app/controllers/copy_controller.js [hunk 2]
```diff
@@ -125,6 +125,11 @@ function handleCopyFrom (logger) {
                     pgstream.emit('error', err);
                 })
                 .pipe(isGzip ? zlib.createGunzip() : new PassThrough())
+                .on('error', err => {
+                    err.message = `Error while gunzipping: ${err.message}`;
```
Comment (rafatower) [inline app/controllers/copy_controller.js]: nice!
